# Generated by Django 2.2 on 2020-02-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_car_car_w_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='All_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='In_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='Out_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
