# Generated by Django 2.2 on 2020-02-13 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200213_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='All_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='In_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 13, 11, 45, 22, 370967)),
        ),
        migrations.AlterField(
            model_name='parking',
            name='Out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='P_Money',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='P_price',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
    ]
