# Generated by Django 2.2 on 2020-02-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200213_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='All_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='In_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='Out_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
