# Generated by Django 2.2 on 2020-02-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20200213_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_w',
            name='Car_w_length',
            field=models.FloatField(max_length=16),
        ),
    ]
