# Generated by Django 2.2 on 2020-02-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20200213_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Car_length',
            field=models.FloatField(max_length=32),
        ),
    ]
