# Generated by Django 2.2 on 2020-02-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20200213_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='P_price',
            field=models.FloatField(blank=True, default=1.5, max_length=8, null=True),
        ),
    ]
