# Generated by Django 2.2 on 2020-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20200213_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='Out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
